In [1]:
import h5py
from IPython.core.display_functions import display

In [2]:
import numpy as np
filename = "../data/example_data.h5"
with h5py.File(filename, "r") as result_file:
    display(result_file)
    display(result_file.keys())
    display(result_file['G'].keys())
    display(result_file['G']['axis0'])
    display(result_file['G']['axis1'])
    display(np.array(result_file['G']['block0_items']))
    display(np.array(result_file['G']['block0_values']))
    display(np.array(result_file['G']['axis0']))
    display(np.array(result_file['G']['axis1']))
    column_names = np.array(result_file['G']['axis0'])
    data = np.array(result_file['G']['block0_values'])
    times = np.array(result_file['G']['axis1'])

array([b'OOA', b'HOA', b'COA'], dtype='|S3')

array([[7.78244990e+00, 3.03673550e-01, 3.32221428e-01],
       [1.78823078e+01, 1.31392228e-01, 1.22018873e+00],
       [2.09208744e+01, 1.17749664e-02, 8.46358221e-01],
       [2.48097876e+01, 8.88021616e-02, 6.56334248e-01],
       [1.47371520e+01, 3.51478351e-01, 1.90492480e+00],
       [2.87892069e+01, 7.55421966e-01, 1.67768853e+00],
       [2.53362071e+01, 2.27150460e+00, 6.33076286e-01],
       [1.65539590e+01, 3.52046632e+00, 6.54661207e-01],
       [6.72774118e+00, 3.37131133e+00, 4.18926534e-01],
       [4.69058681e-01, 3.28817907e+00, 1.12952489e+00],
       [1.38344420e+00, 2.67746724e+00, 1.98876268e+00],
       [3.71773265e+00, 2.07559750e+00, 2.52966218e+00],
       [1.79627553e+01, 1.62944599e+00, 1.41252468e+00],
       [1.27663471e+01, 1.99698773e+00, 1.81279371e+00],
       [6.43589245e+00, 1.39869071e+00, 1.29398986e+00],
       [6.71765015e-01, 1.15375374e+00, 6.35621620e-01],
       [2.70113828e+00, 1.10913742e+00, 5.47521790e-01],
       [7.64573466e+00, 1.00785411e+00, 1.43551184e+00],
       [1.32529086e+01, 5.18584292e-01, 2.92231081e+00],
       [1.26815750e+01, 6.75768827e-01, 3.92571028e+00],
       [1.79179507e+01, 9.49556831e-01, 4.03427620e+00],
       [6.22411838e+00, 5.98042289e-01, 2.74791723e+00],
       [1.97803151e-01, 3.91997597e-01, 1.47667102e+00],
       [8.49219029e+00, 1.60095976e+00, 6.69511536e-01],
       [2.77371276e+00, 2.43118774e+00, 2.29976985e-01],
       [1.80638313e+00, 1.90765700e+00, 4.07281930e-01],
       [4.22595100e+00, 8.59991498e-01, 8.39820049e-01],
       [1.32208619e+00, 9.68670096e-01, 3.86169827e-01],
       [6.57371579e+00, 7.88495229e-01, 1.86450883e-01],
       [3.18745594e+00, 1.61536956e+00, 3.23063201e-01],
       [4.43905016e-01, 2.46776094e+00, 4.34672168e-01],
       [1.94762715e+00, 2.99149402e+00, 1.06176788e+00],
       [3.22088346e+00, 2.73844625e+00, 6.57202516e-01],
       [3.23072542e+00, 2.34461947e+00, 2.29088927e+00],
       [4.02902427e+00, 2.08845349e+00, 4.10594266e+00],
       [2.58107127e-01, 1.96046828e+00, 3.51186535e+00],
       [6.49993833e+00, 1.28307426e+00, 2.36464802e+00],
       [1.83827654e+00, 1.47894102e+00, 2.76287893e+00],
       [2.83804387e+00, 1.74776157e+00, 2.53677522e+00],
       [3.78483094e+00, 1.94016182e+00, 2.56153065e+00],
       [1.77348804e+00, 2.05106064e+00, 2.65656420e+00],
       [1.19100415e+01, 1.93916886e+00, 3.15581444e+00],
       [5.83582028e+00, 1.15736691e+00, 4.71754691e+00],
       [6.39285504e+00, 1.13290595e-01, 8.48735138e+00],
       [2.73075182e+00, 1.36613219e-01, 9.05447663e+00],
       [4.70147912e+00, 4.10779354e-01, 8.03413237e+00],
       [5.89843633e+00, 1.20008981e+00, 6.06535429e+00],
       [3.26107835e+00, 9.54771110e-01, 5.56648135e+00],
       [1.19584612e+01, 3.98722029e-01, 4.29734777e+00],
       [1.30443076e+01, 3.41089835e-01, 3.24408413e+00],
       [2.10638454e+01, 1.53088102e+00, 3.22074372e+00],
       [3.18890602e+01, 1.44859213e+00, 3.00510473e+00],
       [1.84377633e+01, 1.05339673e+00, 2.44471353e+00],
       [1.13558758e+01, 2.18140253e+00, 2.72124571e+00],
       [1.23081078e+01, 2.72455482e+00, 2.23417282e+00],
       [9.49082666e+00, 2.96794200e+00, 2.55803801e+00],
       [2.36065252e+01, 2.59779777e+00, 2.89777402e+00],
       [3.27784355e+01, 1.77085212e+00, 2.92117284e+00],
       [3.73400069e+01, 7.89044458e-01, 2.80627694e+00],
       [3.84273342e+01, 9.71812915e-01, 2.53760451e+00],
       [3.84221351e+01, 1.18940710e+00, 2.76518266e+00],
       [2.94741336e+01, 3.43142443e-01, 2.53985268e+00],
       [1.45426281e+01, 4.96709262e-01, 2.80199389e+00],
       [1.44760290e+01, 3.46822864e-01, 2.35733227e+00],
       [1.12034531e+01, 2.61972011e-01, 2.12876530e+00],
       [5.04690778e+00, 1.26505385e+00, 2.94744991e+00],
       [1.41630387e+01, 1.64768909e+00, 5.23297979e+00],
       [2.04149934e+01, 1.31128567e+00, 7.20200820e+00],
       [2.49329942e+01, 1.10495602e+00, 7.22563247e+00],
       [2.55380171e+01, 1.10104733e-01, 5.97380388e+00],
       [1.83733664e+01, 1.33279683e-01, 4.30876427e+00],
       [7.15963496e+00, 9.41627999e-01, 3.95239869e+00],
       [3.24433669e+00, 1.20811990e+00, 3.54924098e+00],
       [1.67172144e+01, 1.55065701e+00, 2.60110356e+00],
       [9.12591620e+00, 1.63614789e+00, 2.58152358e+00],
       [5.64238985e+00, 2.31391592e+00, 2.90059162e+00],
       [3.66845217e+00, 1.88838920e+00, 3.31199018e+00],
       [2.31750299e+00, 2.23424740e+00, 3.01263152e+00],
       [2.19494018e+00, 2.46767280e+00, 2.52365559e+00],
       [5.19005027e+00, 3.83027351e+00, 3.03374379e+00],
       [9.79539043e+00, 3.60213857e+00, 2.95746692e+00],
       [2.03026482e+01, 1.88709727e+00, 2.81928545e+00],
       [2.18131652e+01, 1.18110595e+00, 2.77103589e+00],
       [1.82477121e+01, 6.48034377e-01, 3.25523422e+00],
       [3.19728525e+01, 4.37836068e-01, 2.55499200e+00],
       [2.80762446e+01, 1.60507141e-01, 1.39779650e+00],
       [3.38719000e+01, 2.25447747e-01, 7.91834998e-01],
       [1.34247527e+01, 4.64407809e-01, 1.48726216e+00],
       [1.21052021e+01, 1.05620296e+00, 1.49259784e+00],
       [1.32420588e+01, 3.09115383e+00, 1.61707642e+00],
       [1.76001383e+01, 3.66019455e+00, 3.00011648e+00],
       [2.16707032e+01, 4.05889850e+00, 4.46396673e+00],
       [1.51927615e+01, 3.08722876e+00, 5.10417834e+00],
       [7.07578816e+00, 3.05503563e+00, 4.18360716e+00],
       [1.75825065e-01, 2.90184172e+00, 2.69229676e+00],
       [5.81296018e+00, 3.42685332e+00, 2.79791035e+00],
       [1.91862276e+01, 2.97680678e+00, 3.01766533e+00],
       [1.92032688e+01, 2.07008056e+00, 2.32505590e+00],
       [1.70180422e+01, 1.92725988e+00, 2.70386635e+00],
       [2.39585349e+01, 1.96938744e+00, 3.15312849e+00],
       [1.02350747e+01, 1.48419467e+00, 3.36604268e+00],
       [5.36676551e+00, 1.51280047e+00, 3.53008670e+00],
       [1.08504206e+01, 1.77712390e+00, 3.24923472e+00],
       [1.40632534e+01, 3.30257532e+00, 2.69902995e+00],
       [1.43021183e+01, 3.19945907e+00, 2.13574132e+00],
       [1.36090916e+01, 2.26534480e+00, 1.82544872e+00],
       [6.03867530e+00, 1.00136222e+00, 1.25450644e+00],
       [2.20866179e+00, 9.21024870e-01, 2.06297849e+00],
       [9.81842866e+00, 2.76501680e-01, 2.05767048e+00],
       [1.68908976e+01, 8.71778373e-02, 1.30040204e+00],
       [2.89480841e+01, 2.57805424e-01, 1.44196564e+00],
       [3.66750589e+01, 1.05656580e-01, 1.11743595e+00],
       [2.78830523e+01, 3.23957670e-01, 6.11978058e-01],
       [2.05883180e+01, 1.57140555e+00, 1.36167316e+00],
       [1.63826021e+01, 1.69136431e+00, 2.78972682e+00],
       [1.21082893e+01, 2.45373751e+00, 4.17968908e+00],
       [1.45566402e+01, 2.41380215e+00, 4.47974406e+00],
       [1.80674383e+01, 1.42086657e+00, 2.90518174e+00],
       [2.68831752e+01, 1.35695734e+00, 1.32090343e+00],
       [2.24552282e+01, 1.01589993e+00, 3.46378221e-01],
       [2.98230793e+01, 3.51151846e-01, 1.79207908e-01],
       [3.19915119e+01, 1.35000346e+00, 5.42909133e-02],
       [3.73462953e+01, 1.63261488e+00, 6.11607932e-02],
       [4.37598588e+01, 1.11593477e+00, 1.89118053e-01],
       [4.21450648e+01, 8.43168393e-01, 2.21355973e-01],
       [3.60540066e+01, 9.15040106e-01, 1.31307007e-01],
       [3.67856315e+01, 2.29367227e+00, 1.03061594e-01],
       [3.18462879e+01, 2.78718586e+00, 3.52809030e-01],
       [3.91584212e+01, 2.99032566e+00, 3.65393312e-01],
       [5.04606218e+01, 1.99018574e+00, 5.00378925e-01],
       [5.86124599e+01, 1.50600981e+00, 1.37959243e+00],
       [4.75353493e+01, 1.74570359e+00, 1.50889953e+00],
       [4.77450700e+01, 1.68074607e+00, 2.33339573e+00],
       [5.87951398e+01, 1.55875449e+00, 2.08244274e+00],
       [5.24260078e+01, 2.20127324e+00, 1.85755821e+00],
       [4.75348538e+01, 2.51698537e+00, 1.59434437e+00],
       [4.30580450e+01, 2.03102168e+00, 1.86755453e+00],
       [4.73347093e+01, 1.64895333e+00, 2.08680567e+00],
       [6.20680343e+01, 1.59457997e+00, 2.92897083e+00],
       [5.87539904e+01, 1.28717696e+00, 4.00838641e+00],
       [6.13394015e+01, 6.06252034e-01, 4.51184521e+00],
       [5.68929592e+01, 2.10542864e-01, 3.64042233e+00],
       [5.68517491e+01, 2.77532918e-02, 1.86977510e+00],
       [4.09130438e+01, 1.01859457e-01, 8.39163472e-01],
       [3.13932381e+01, 1.51711230e-01, 2.68271428e-01],
       [2.69340942e+01, 1.10952559e-01, 6.38338949e-02],
       [2.50191955e+01, 7.26617957e-01, 1.14494887e-01],
       [2.19866849e+01, 1.34814076e+00, 2.26921563e-01],
       [2.07084110e+01, 1.36191931e+00, 3.66088245e-01],
       [4.40147507e+00, 2.12605630e+00, 9.38259252e-02],
       [2.72215521e+00, 3.01075095e+00, 1.00188828e-01],
       [5.72016188e+00, 3.85234196e+00, 2.03241848e-01],
       [1.17451261e+01, 4.93882232e+00, 5.50413465e-01],
       [2.07655201e+00, 3.79522698e+00, 1.00133568e+00],
       [1.56158052e+00, 2.72253997e+00, 9.00586401e-01],
       [3.50019005e+00, 1.55611992e+00, 1.74816954e+00],
       [1.65888206e+01, 9.27266767e-01, 2.40440860e+00],
       [2.10662107e+01, 6.04380576e-01, 2.41480145e+00],
       [1.63269295e+01, 7.31592748e-01, 2.54074936e+00],
       [1.86452041e+01, 9.66888516e-01, 2.65291942e+00],
       [2.69562290e+01, 8.10273361e-01, 2.51430668e+00],
       [9.06771318e+00, 1.53627049e+00, 1.77857428e+00],
       [4.75302409e+00, 1.82614863e+00, 2.89044114e+00],
       [1.49165877e+01, 1.93032363e+00, 4.94785234e+00],
       [9.93722429e+00, 1.57605286e+00, 5.49030972e+00],
       [2.20705776e+01, 8.15308730e-01, 4.14997514e+00],
       [2.83960768e+01, 1.04557842e+00, 2.52105355e+00],
       [3.73738111e+01, 8.20699082e-01, 8.22740044e-01]])

array([b'OOA', b'HOA', b'COA'], dtype='|S3')

array([1546300800000000000, 1546304400000000000, 1546308000000000000,
       1546311600000000000, 1546315200000000000, 1546318800000000000,
       1546322400000000000, 1546326000000000000, 1546329600000000000,
       1546333200000000000, 1546336800000000000, 1546340400000000000,
       1546344000000000000, 1546347600000000000, 1546351200000000000,
       1546354800000000000, 1546358400000000000, 1546362000000000000,
       1546365600000000000, 1546369200000000000, 1546372800000000000,
       1546376400000000000, 1546380000000000000, 1546383600000000000,
       1546387200000000000, 1546390800000000000, 1546394400000000000,
       1546398000000000000, 1546401600000000000, 1546405200000000000,
       1546408800000000000, 1546412400000000000, 1546416000000000000,
       1546419600000000000, 1546423200000000000, 1546426800000000000,
       1546430400000000000, 1546434000000000000, 1546437600000000000,
       1546441200000000000, 1546444800000000000, 1546448400000000000,
       1546452000000000000, 1546455600000000000, 1546459200000000000,
       1546462800000000000, 1546466400000000000, 1546470000000000000,
       1546473600000000000, 1546477200000000000, 1546480800000000000,
       1546484400000000000, 1546488000000000000, 1546491600000000000,
       1546495200000000000, 1546498800000000000, 1546502400000000000,
       1546506000000000000, 1546509600000000000, 1546513200000000000,
       1546516800000000000, 1546520400000000000, 1546524000000000000,
       1546527600000000000, 1546531200000000000, 1546534800000000000,
       1546538400000000000, 1546542000000000000, 1546545600000000000,
       1546549200000000000, 1546552800000000000, 1546556400000000000,
       1546560000000000000, 1546563600000000000, 1546567200000000000,
       1546570800000000000, 1546574400000000000, 1546578000000000000,
       1546581600000000000, 1546585200000000000, 1546588800000000000,
       1546592400000000000, 1546596000000000000, 1546599600000000000,
       1546603200000000000, 1546606800000000000, 1546610400000000000,
       1546614000000000000, 1546617600000000000, 1546621200000000000,
       1546624800000000000, 1546628400000000000, 1546632000000000000,
       1546635600000000000, 1546639200000000000, 1546642800000000000,
       1546646400000000000, 1546650000000000000, 1546653600000000000,
       1546657200000000000, 1546660800000000000, 1546664400000000000,
       1546668000000000000, 1546671600000000000, 1546675200000000000,
       1546678800000000000, 1546682400000000000, 1546686000000000000,
       1546689600000000000, 1546693200000000000, 1546696800000000000,
       1546700400000000000, 1546704000000000000, 1546707600000000000,
       1546711200000000000, 1546714800000000000, 1546718400000000000,
       1546722000000000000, 1546725600000000000, 1546729200000000000,
       1546732800000000000, 1546736400000000000, 1546740000000000000,
       1546743600000000000, 1546747200000000000, 1546750800000000000,
       1546754400000000000, 1546758000000000000, 1546761600000000000,
       1546765200000000000, 1546768800000000000, 1546772400000000000,
       1546776000000000000, 1546779600000000000, 1546783200000000000,
       1546786800000000000, 1546790400000000000, 1546794000000000000,
       1546797600000000000, 1546801200000000000, 1546804800000000000,
       1546808400000000000, 1546812000000000000, 1546815600000000000,
       1546819200000000000, 1546822800000000000, 1546826400000000000,
       1546830000000000000, 1546833600000000000, 1546837200000000000,
       1546840800000000000, 1546844400000000000, 1546848000000000000,
       1546851600000000000, 1546855200000000000, 1546858800000000000,
       1546862400000000000, 1546866000000000000, 1546869600000000000,
       1546873200000000000, 1546876800000000000, 1546880400000000000,
       1546884000000000000, 1546887600000000000, 1546891200000000000,
       1546894800000000000, 1546898400000000000, 1546902000000000000])

In [21]:
import pandas as pd

test_G = pd.DataFrame(columns = column_names, index = times, data=data)
test_G

                        b'OOA'    b'HOA'    b'COA'
1546300800000000000   7.782450  0.303674  0.332221
1546304400000000000  17.882308  0.131392  1.220189
1546308000000000000  20.920874  0.011775  0.846358
1546311600000000000  24.809788  0.088802  0.656334
1546315200000000000  14.737152  0.351478  1.904925
...                        ...       ...       ...
1546887600000000000  14.916588  1.930324  4.947852
1546891200000000000   9.937224  1.576053  5.490310
1546894800000000000  22.070578  0.815309  4.149975
1546898400000000000  28.396077  1.045578  2.521054
1546902000000000000  37.373811  0.820699  0.822740

[168 rows x 3 columns]

In [22]:
with h5py.File(filename, "r") as result_file:
    display(result_file)
    display(result_file.keys())
    display(result_file['F'].keys())
    display(result_file['F']['axis0'])
    display(result_file['F']['axis1'])
    display(np.array(result_file['F']['block0_items']))
    display(np.array(result_file['F']['block0_values']))
    display(np.array(result_file['F']['axis0']))
    display(np.array(result_file['F']['axis1']))
    column_names = np.array(result_file['F']['axis0'])
    data = np.array(result_file['F']['block0_values'])
    times = np.array(result_file['F']['axis1'])

array([12, 13, 15, 22, 24, 25, 26, 27, 29, 30, 31, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65])

array([[1.38172794e-02, 6.43510830e-03, 4.37909231e-02, 5.35337381e-04,
        1.45110758e-03, 5.10269117e-03, 2.74779181e-02, 6.27325894e-02,
        1.27739737e-01, 5.47102800e-02, 3.54825920e-02, 5.12281468e-03,
        8.89739504e-03, 4.00116127e-02, 9.01250372e-03, 4.32520587e-02,
        3.54940071e-02, 1.26835204e-01, 1.63611511e-01, 2.35198200e-02,
        3.89403227e-03, 4.22909559e-03, 1.49942041e-03, 8.61325979e-03,
        9.48081285e-03, 6.23837089e-03, 1.47097545e-02, 1.01726406e-02,
        3.50578032e-02, 1.01349282e-02, 1.98562821e-02, 8.92428038e-03,
        4.90084619e-03, 5.96457027e-03, 3.07332954e-03, 2.64747227e-03,
        8.17888708e-03, 2.04975637e-03, 5.34196629e-03],
       [5.43712606e-03, 2.04757387e-03, 2.63943249e-02, 2.07143191e-04,
        7.46898456e-04, 2.04298140e-03, 1.07088743e-02, 4.50866382e-02,
        6.70525030e-02, 1.96551376e-02, 1.07318041e-02, 3.18057853e-03,
        6.73850499e-03, 3.83816484e-02, 5.50404258e-03, 1.28102843e-01,
        2.77185034e-02, 1.80330007e-01, 5.60874618e-02, 3.37645081e-03,
        8.44700150e-04, 1.04746258e-03, 7.99228184e-04, 7.05437572e-03,
        6.46442248e-03, 2.20947797e-03, 1.42005536e-02, 1.27657139e-02,
        1.21084097e-01, 2.56469445e-02, 1.35292340e-01, 7.99400087e-03,
        1.89127754e-03, 3.56962055e-03, 1.63370413e-03, 2.51058928e-03,
        5.60735849e-03, 1.37325272e-03, 8.47983447e-03],
       [7.11892599e-03, 3.37350581e-03, 9.33321549e-03, 2.68024522e-04,
        9.44726785e-04, 4.49509966e-03, 2.42869312e-02, 8.81132523e-02,
        9.42632369e-02, 2.54397043e-07, 3.84649723e-03, 5.14278375e-03,
        8.29776820e-03, 7.24774591e-02, 1.43577551e-02, 1.56118259e-01,
        3.83273245e-02, 9.99027557e-02, 1.84461384e-02, 1.00273161e-02,
        6.10982978e-04, 0.00000000e+00, 8.95319896e-04, 5.25910234e-03,
        8.57109394e-03, 6.58375382e-03, 2.42827838e-02, 3.33185745e-02,
        1.56214414e-01, 2.37288554e-02, 4.44712381e-02, 4.40776841e-03,
        3.56333055e-03, 1.11773578e-02, 2.29257858e-03, 1.15346156e-03,
        3.25051697e-03, 3.64110464e-04, 1.07135261e-02]])

array([12, 13, 15, 22, 24, 25, 26, 27, 29, 30, 31, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65])

array([b'OOA', b'HOA', b'COA'], dtype='|S3')

In [23]:
import pandas as pd

test_F = pd.DataFrame(columns = column_names, index = times, data=data)
test_F

,12,13,15,22,24,25,26,27,29,30,...,56,57,58,59,60,61,62,63,64,65
b'OOA',0.013817,0.006435,0.043791,0.000535,0.001451,0.005103,0.027478,0.062733,0.127740,5.471028e-02,...,0.010135,0.019856,0.008924,0.004901,0.005965,0.003073,0.002647,0.008179,0.002050,0.005342
b'HOA',0.005437,0.002048,0.026394,0.000207,0.000747,0.002043,0.010709,0.045087,0.067053,1.965514e-02,...,0.025647,0.135292,0.007994,0.001891,0.003570,0.001634,0.002511,0.005607,0.001373,0.008480
b'COA',0.007119,0.003374,0.009333,0.000268,0.000945,0.004495,0.024287,0.088113,0.094263,2.543970e-07,...,0.023729,0.044471,0.004408,0.003563,0.011177,0.002293,0.001153,0.003251,0.000364,0.010714

In [24]:
test_F.to_csv("../data/example_data_F.csv")
test_G.to_csv("../data/example_data_G.csv")

In [3]:
with h5py.File(filename, "r") as result_file:
    display(result_file)
    display(result_file.keys())
    display(result_file['error'].keys())
    display(result_file['error']['axis0'])
    display(result_file['error']['axis1'])
    display(np.array(result_file['error']['block0_items']))
    display(np.array(result_file['error']['block0_values']))
    display(np.array(result_file['error']['axis0']))
    display(np.array(result_file['error']['axis1']))
    column_names = np.array(result_file['error']['axis0'])
    data = np.array(result_file['error']['block0_values'])
    times = np.array(result_file['error']['axis1'])

array([12, 13, 15, 22, 24, 25, 26, 27, 29, 30, 31, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65])

array([[0.00557742, 0.00259117, 0.01759583, ..., 0.00332172, 0.00082451,
        0.0023854 ],
       [0.01282428, 0.005973  , 0.03989695, ..., 0.00754802, 0.00186395,
        0.00548567],
       [0.01475794, 0.00687537, 0.04621772, ..., 0.00869633, 0.00216035,
        0.0060463 ],
       ...,
       [0.01694658, 0.0078848 , 0.05133716, ..., 0.0099287 , 0.0023935 ,
        0.00846374],
       [0.02079943, 0.00966888, 0.06473086, ..., 0.0123153 , 0.00302794,
        0.00937833],
       [0.02633618, 0.01224802, 0.08329871, ..., 0.01564762, 0.00390169,
        0.01077117]])

array([12, 13, 15, 22, 24, 25, 26, 27, 29, 30, 31, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65])

array([1546300800000000000, 1546304400000000000, 1546308000000000000,
       1546311600000000000, 1546315200000000000, 1546318800000000000,
       1546322400000000000, 1546326000000000000, 1546329600000000000,
       1546333200000000000, 1546336800000000000, 1546340400000000000,
       1546344000000000000, 1546347600000000000, 1546351200000000000,
       1546354800000000000, 1546358400000000000, 1546362000000000000,
       1546365600000000000, 1546369200000000000, 1546372800000000000,
       1546376400000000000, 1546380000000000000, 1546383600000000000,
       1546387200000000000, 1546390800000000000, 1546394400000000000,
       1546398000000000000, 1546401600000000000, 1546405200000000000,
       1546408800000000000, 1546412400000000000, 1546416000000000000,
       1546419600000000000, 1546423200000000000, 1546426800000000000,
       1546430400000000000, 1546434000000000000, 1546437600000000000,
       1546441200000000000, 1546444800000000000, 1546448400000000000,
       1546452000000000000, 1546455600000000000, 1546459200000000000,
       1546462800000000000, 1546466400000000000, 1546470000000000000,
       1546473600000000000, 1546477200000000000, 1546480800000000000,
       1546484400000000000, 1546488000000000000, 1546491600000000000,
       1546495200000000000, 1546498800000000000, 1546502400000000000,
       1546506000000000000, 1546509600000000000, 1546513200000000000,
       1546516800000000000, 1546520400000000000, 1546524000000000000,
       1546527600000000000, 1546531200000000000, 1546534800000000000,
       1546538400000000000, 1546542000000000000, 1546545600000000000,
       1546549200000000000, 1546552800000000000, 1546556400000000000,
       1546560000000000000, 1546563600000000000, 1546567200000000000,
       1546570800000000000, 1546574400000000000, 1546578000000000000,
       1546581600000000000, 1546585200000000000, 1546588800000000000,
       1546592400000000000, 1546596000000000000, 1546599600000000000,
       1546603200000000000, 1546606800000000000, 1546610400000000000,
       1546614000000000000, 1546617600000000000, 1546621200000000000,
       1546624800000000000, 1546628400000000000, 1546632000000000000,
       1546635600000000000, 1546639200000000000, 1546642800000000000,
       1546646400000000000, 1546650000000000000, 1546653600000000000,
       1546657200000000000, 1546660800000000000, 1546664400000000000,
       1546668000000000000, 1546671600000000000, 1546675200000000000,
       1546678800000000000, 1546682400000000000, 1546686000000000000,
       1546689600000000000, 1546693200000000000, 1546696800000000000,
       1546700400000000000, 1546704000000000000, 1546707600000000000,
       1546711200000000000, 1546714800000000000, 1546718400000000000,
       1546722000000000000, 1546725600000000000, 1546729200000000000,
       1546732800000000000, 1546736400000000000, 1546740000000000000,
       1546743600000000000, 1546747200000000000, 1546750800000000000,
       1546754400000000000, 1546758000000000000, 1546761600000000000,
       1546765200000000000, 1546768800000000000, 1546772400000000000,
       1546776000000000000, 1546779600000000000, 1546783200000000000,
       1546786800000000000, 1546790400000000000, 1546794000000000000,
       1546797600000000000, 1546801200000000000, 1546804800000000000,
       1546808400000000000, 1546812000000000000, 1546815600000000000,
       1546819200000000000, 1546822800000000000, 1546826400000000000,
       1546830000000000000, 1546833600000000000, 1546837200000000000,
       1546840800000000000, 1546844400000000000, 1546848000000000000,
       1546851600000000000, 1546855200000000000, 1546858800000000000,
       1546862400000000000, 1546866000000000000, 1546869600000000000,
       1546873200000000000, 1546876800000000000, 1546880400000000000,
       1546884000000000000, 1546887600000000000, 1546891200000000000,
       1546894800000000000, 1546898400000000000, 1546902000000000000])

In [5]:
import pandas as pd

test_E = pd.DataFrame(columns=column_names, index= times, data=data)
test_E

,12,13,15,22,24,25,26,27,29,30,...,56,57,58,59,60,61,62,63,64,65
1546300800000000000,0.005577,0.002591,0.017596,0.000216,0.000592,0.002091,0.011258,0.026559,0.052290,0.021587,...,0.004727,0.010519,0.003667,0.001995,0.002561,0.001259,0.001087,0.003322,0.000825,0.002385
1546304400000000000,0.012824,0.005973,0.039897,0.000496,0.001360,0.004850,0.026121,0.061762,0.120406,0.049046,...,0.010678,0.021356,0.008301,0.004612,0.006038,0.002899,0.002454,0.007548,0.001864,0.005486
1546308000000000000,0.014758,0.006875,0.046218,0.000571,0.001558,0.005529,0.029777,0.069376,0.137650,0.057241,...,0.011621,0.022732,0.009526,0.005278,0.006714,0.003313,0.002820,0.008696,0.002160,0.006046
1546311600000000000,0.017398,0.008102,0.054746,0.000674,0.001834,0.006486,0.034931,0.080911,0.161851,0.067955,...,0.013465,0.026692,0.011251,0.006205,0.007782,0.003895,0.003333,0.010277,0.002561,0.007016
1546315200000000000,0.010955,0.005099,0.033620,0.000424,0.001172,0.004224,0.022749,0.055410,0.104283,0.040659,...,0.010179,0.021245,0.007136,0.003984,0.005522,0.002512,0.002105,0.006435,0.001569,0.005106
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1546887600000000000,0.012591,0.005832,0.037517,0.000486,0.001388,0.005115,0.027536,0.072938,0.125064,0.042702,...,0.015905,0.038869,0.008518,0.004719,0.007558,0.003017,0.002502,0.007445,0.001751,0.007453
1546891200000000000,0.009248,0.004285,0.026400,0.000356,0.001039,0.003930,0.021164,0.058911,0.094630,0.028732,...,0.013571,0.032735,0.006274,0.003562,0.006313,0.002285,0.001830,0.005398,0.001227,0.006263
1546894800000000000,0.016947,0.007885,0.051337,0.000655,0.001828,0.006647,0.035799,0.089349,0.163257,0.061176,...,0.017153,0.036655,0.011089,0.006225,0.009047,0.003934,0.003263,0.009929,0.002393,0.008464
1546898400000000000,0.020799,0.009669,0.064731,0.000805,0.002218,0.007918,0.042635,0.102532,0.196753,0.078705,...,0.018721,0.040871,0.013644,0.007506,0.010064,0.004738,0.004036,0.012315,0.003028,0.009378
1546902000000000000,0.026336,0.012248,0.083299,0.001020,0.002781,0.009804,0.052786,0.122703,0.245335,0.103043,...,0.020968,0.044486,0.017186,0.009382,0.011752,0.005904,0.005098,0.015648,0.003902,0.010771

In [7]:
test_E.to_csv("../data/example_data_E.csv")

In [8]:
with h5py.File(filename, "r") as result_file:
    display(result_file)
    display(result_file.keys())
    display(result_file['data'].keys())
    display(result_file['data']['axis0'])
    display(result_file['data']['axis1'])
    display(np.array(result_file['data']['block0_items']))
    display(np.array(result_file['data']['block0_values']))
    display(np.array(result_file['data']['axis0']))
    display(np.array(result_file['data']['axis1']))
    column_names = np.array(result_file['data']['axis0'])
    data = np.array(result_file['data']['block0_values'])
    times = np.array(result_file['data']['axis1'])

array([12, 13, 15, 22, 24, 25, 26, 27, 29, 30, 31, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65])

array([[0.10251398, 0.04499366, 0.32195827, ..., 0.06832715, 0.01608007,
        0.04625703],
       [0.26038729, 0.12619608, 0.81785179, ..., 0.14332171, 0.03655551,
        0.11157969],
       [0.29090711, 0.14149428, 0.97227191, ..., 0.16027196, 0.04490678,
        0.12545816],
       ...,
       [0.32289251, 0.16081402, 1.04743141, ..., 0.19834812, 0.04934584,
        0.17845328],
       [0.34560254, 0.19366475, 1.25918314, ..., 0.24513883, 0.06051161,
        0.20264107],
       [0.52599329, 0.24051968, 1.7123395 , ..., 0.3223134 , 0.07967591,
        0.20905953]])

array([12, 13, 15, 22, 24, 25, 26, 27, 29, 30, 31, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65])

array([1546300800000000000, 1546304400000000000, 1546308000000000000,
       1546311600000000000, 1546315200000000000, 1546318800000000000,
       1546322400000000000, 1546326000000000000, 1546329600000000000,
       1546333200000000000, 1546336800000000000, 1546340400000000000,
       1546344000000000000, 1546347600000000000, 1546351200000000000,
       1546354800000000000, 1546358400000000000, 1546362000000000000,
       1546365600000000000, 1546369200000000000, 1546372800000000000,
       1546376400000000000, 1546380000000000000, 1546383600000000000,
       1546387200000000000, 1546390800000000000, 1546394400000000000,
       1546398000000000000, 1546401600000000000, 1546405200000000000,
       1546408800000000000, 1546412400000000000, 1546416000000000000,
       1546419600000000000, 1546423200000000000, 1546426800000000000,
       1546430400000000000, 1546434000000000000, 1546437600000000000,
       1546441200000000000, 1546444800000000000, 1546448400000000000,
       1546452000000000000, 1546455600000000000, 1546459200000000000,
       1546462800000000000, 1546466400000000000, 1546470000000000000,
       1546473600000000000, 1546477200000000000, 1546480800000000000,
       1546484400000000000, 1546488000000000000, 1546491600000000000,
       1546495200000000000, 1546498800000000000, 1546502400000000000,
       1546506000000000000, 1546509600000000000, 1546513200000000000,
       1546516800000000000, 1546520400000000000, 1546524000000000000,
       1546527600000000000, 1546531200000000000, 1546534800000000000,
       1546538400000000000, 1546542000000000000, 1546545600000000000,
       1546549200000000000, 1546552800000000000, 1546556400000000000,
       1546560000000000000, 1546563600000000000, 1546567200000000000,
       1546570800000000000, 1546574400000000000, 1546578000000000000,
       1546581600000000000, 1546585200000000000, 1546588800000000000,
       1546592400000000000, 1546596000000000000, 1546599600000000000,
       1546603200000000000, 1546606800000000000, 1546610400000000000,
       1546614000000000000, 1546617600000000000, 1546621200000000000,
       1546624800000000000, 1546628400000000000, 1546632000000000000,
       1546635600000000000, 1546639200000000000, 1546642800000000000,
       1546646400000000000, 1546650000000000000, 1546653600000000000,
       1546657200000000000, 1546660800000000000, 1546664400000000000,
       1546668000000000000, 1546671600000000000, 1546675200000000000,
       1546678800000000000, 1546682400000000000, 1546686000000000000,
       1546689600000000000, 1546693200000000000, 1546696800000000000,
       1546700400000000000, 1546704000000000000, 1546707600000000000,
       1546711200000000000, 1546714800000000000, 1546718400000000000,
       1546722000000000000, 1546725600000000000, 1546729200000000000,
       1546732800000000000, 1546736400000000000, 1546740000000000000,
       1546743600000000000, 1546747200000000000, 1546750800000000000,
       1546754400000000000, 1546758000000000000, 1546761600000000000,
       1546765200000000000, 1546768800000000000, 1546772400000000000,
       1546776000000000000, 1546779600000000000, 1546783200000000000,
       1546786800000000000, 1546790400000000000, 1546794000000000000,
       1546797600000000000, 1546801200000000000, 1546804800000000000,
       1546808400000000000, 1546812000000000000, 1546815600000000000,
       1546819200000000000, 1546822800000000000, 1546826400000000000,
       1546830000000000000, 1546833600000000000, 1546837200000000000,
       1546840800000000000, 1546844400000000000, 1546848000000000000,
       1546851600000000000, 1546855200000000000, 1546858800000000000,
       1546862400000000000, 1546866000000000000, 1546869600000000000,
       1546873200000000000, 1546876800000000000, 1546880400000000000,
       1546884000000000000, 1546887600000000000, 1546891200000000000,
       1546894800000000000, 1546898400000000000, 1546902000000000000])

In [9]:

test_X = pd.DataFrame(columns=column_names, index= times, data=data)
test_X

,12,13,15,22,24,25,26,27,29,30,...,56,57,58,59,60,61,62,63,64,65
1546300800000000000,0.102514,0.044994,0.321958,0.004679,0.011246,0.041215,0.234766,0.528633,1.070516,0.422594,...,0.091543,0.212854,0.077718,0.040790,0.049309,0.022814,0.021536,0.068327,0.016080,0.046257
1546304400000000000,0.260387,0.126196,0.817852,0.010411,0.028757,0.092937,0.519016,1.317085,2.582660,1.034381,...,0.215523,0.418714,0.164939,0.089180,0.117258,0.058673,0.049507,0.143322,0.036556,0.111580
1546308000000000000,0.290907,0.141494,0.972272,0.012172,0.030717,0.102760,0.547183,1.389952,2.524094,1.183674,...,0.238171,0.440775,0.180637,0.101280,0.126614,0.070682,0.060867,0.160272,0.044907,0.125458
1546311600000000000,0.346949,0.162201,1.125009,0.012746,0.040424,0.128113,0.688234,1.611944,3.323981,1.322703,...,0.279740,0.558376,0.223967,0.122660,0.142131,0.066711,0.066087,0.210180,0.051118,0.143118
1546315200000000000,0.186418,0.101166,0.609910,0.009168,0.023260,0.083786,0.410432,1.073119,2.053350,0.860846,...,0.212590,0.454310,0.154283,0.074601,0.112562,0.047591,0.044429,0.135560,0.030822,0.103563
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1546887600000000000,0.244004,0.101680,0.735581,0.010222,0.026497,0.099908,0.600335,1.451413,2.537049,0.837015,...,0.309107,0.707305,0.154161,0.097649,0.159187,0.058309,0.053393,0.144568,0.033987,0.158529
1546891200000000000,0.187626,0.090999,0.555544,0.007613,0.019153,0.082562,0.432956,1.040614,1.951398,0.574228,...,0.268633,0.609422,0.116403,0.070648,0.119181,0.047250,0.035001,0.110488,0.025270,0.124187
1546894800000000000,0.322893,0.160814,1.047431,0.012410,0.037372,0.143091,0.680180,1.729046,3.298958,1.209721,...,0.363206,0.684163,0.221278,0.130621,0.165235,0.073239,0.061261,0.198348,0.049346,0.178453
1546898400000000000,0.345603,0.193665,1.259183,0.015970,0.043067,0.165656,0.846319,2.288777,4.112800,1.479649,...,0.343905,0.822343,0.277202,0.151482,0.219199,0.091250,0.083633,0.245139,0.060512,0.202641
1546902000000000000,0.525993,0.240520,1.712340,0.020398,0.056114,0.198407,1.058325,2.206788,4.758091,2.099549,...,0.409936,0.898269,0.352965,0.190252,0.227157,0.117412,0.109306,0.322313,0.079676,0.209060

In [10]:
test_X.to_csv("../data/example_data_X.csv")